name: Check PR

on:
  # Triggers the workflow on every pull request to develop branch
  pull_request:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  connected-test:
    runs-on: macos-latest
    continue-on-error: true
    env:
      GPR_USER: ${{ secrets.GPR_USER }}
      GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
    strategy:
      matrix:
        api-level: [29, 30]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Write study public key pem file
        env:
          STUDY_PUBLIC_KEY_BASE64: ${{ secrets.STUDY_PUBLIC_KEY_BASE64 }}
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/app/src/main/assets/
          echo "$STUDY_PUBLIC_KEY_BASE64" | base64 --decode > ${GITHUB_WORKSPACE}/app/src/main/assets/study_public_key.pem

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Run unit tests
        run: ./gradlew test --stacktrace

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: ./gradlew connectedCheck --stacktrace

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test-Results
          path: app/build/outputs/androidTest-results
        if: always()

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: app/build/reports
        if: always()